### ISSUE TITLE
[Meta] Blog Relaunch Process

### ISSUE THREAD

**Issue by em-ly** [ipfs/blog#58]
There have been a lot of exciting things happening in the IPFS world, but we've been doing a poor job at capturing all the excitement. This issue is to document the process of rolling out a new blog management flow.

Side Note: We are going to use this process relaunch as a trial experiment using the tool Waffle.io. Once that's operational, I'll update this blurb with a link to that.
**Edit: https://waffle.io/ipfs/blog**

**Current Goals:**
- [x] @RichardLitt to set up new label system as outlined https://github.com/ipfs/blog/issues/57

- [x] @aistich to add labels/clear out open issues and pull requests

- [ ] Open issues for blog posts currently in process, label correctly

- [x] @RichardLitt to set up IPFS bot with Waffle.io
     - [x] import blog issues in Waffle.io/setup boards

**Comment by RichardLitt** [comment]
Not sure that opening issues for blog posts currently in the process makes sense, as we can discuss them in their respective PRs. However, opening individual issues for each idea might be worth doing? Then we can discuss each at length in a threaded manner. I'm happy to automate this, if we want to just do this all at once.

**Comment by em-ly** [comment]
@RichardLitt Is there a way to track PRs the same way that we track issues in Waffle.io? If it can be handled and looks the same way on their end, then I agree that it doesn't make sense to have duplicate ideas/PRs, unless the idea is first generated instead of a skeleton (which in theory should be the process. how else are we getting blog post ideas? i don't see someone jumping straight to make a PR.)

**Comment by RichardLitt** [comment]
@em-ly Yep. Take a look at https://waffle.io/ipfs/blog -- the ones with the PR symbol are PRs. It looks the same. 

I think the idea should first be an issue, to help discussion easier, and then turned into a PR and the idea issue closed.

**Comment by em-ly** [comment]
Agreed! That makes sense of a flow. So it will remain an idea until it's been assigned -> becomes a skeleton PR. the issue should be closed linking to the PR.

For posts that are in the "needs review" stage (i.e. https://github.com/ipfs/blog/pull/15) can we add the relevant content review/tech review/cohesion review/mech review tags? what's the best way to make sure those are all checked off? I was thinking we could add the tags and then remove when the review's happened.

**Comment by RichardLitt** [comment]
Yes, you can add those labels for that stage. When they are done, they should be removed. Should be clear to tell.

**Comment by em-ly** [comment]
Moving this discussion to https://github.com/ipfs/blog/issues/70
