### ISSUE TITLE
[Meta] Blog/Newsletter Discussion

### ISSUE THREAD

**Issue by em-ly** [ipfs/blog#70]
Hi all, I just wanted to capture the discussion that happened last week with regards to getting the ball rolling on the blog and news letter again. Below are the identified action items that we created:

**Action items:**
- [ ] @em-ly to read through blog pipeline and surface any questions
- [ ] @em-ly to assess status of pending blog posts that aren't moving in the pipeline
- [ ] @RichardLitt to put together draft of the Newsletter
- [ ] @RichardLitt to write a blog post to go up this week

**Comment by mishmosh** [comment]
Pipeline is moving again so this is not needed.
